name: Hello World
on: push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
    - name: Echo text
      run: 'echo "Hello, World!"'
    - name: Echo another text
      run: 'echo "Hello World11"'
    - name: Echo 3rd text
      run: 'echo "Hello world22"'
